### ISSUE TITLE
Unlabeled function arguments

### ISSUE THREAD

**Issue by AdaDoom3** [Lucretia/adavulkan#1]
Many functions (or function pointer types) have their arguments incorrectly named "argX"

As a suggestion for making a thick binding - many functions that retrieve information follow the C-pattern of: function call to get buffer size, allocate buffer, then call again with buffer. You can imagine this leads to a lot of declare blocks and gets a little ugly. Besides wrapping up the enumerated types, handling these buffer allocation functions would be very useful.

**Comment by Lucretia** [comment]
I haven't even pushed anything to this repo yet apart from the quickly generated bindings from gcc. I have half edited the bindings.

**Comment by AdaDoom3** [comment]
Hm, I wonder why the generated bindings remove parameter names....

**Comment by Lucretia** [comment]
I have no idea.
